spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/spaceBookingSystem
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/seed
    out-of-order: true
    validate-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,conditions
  endpoint:
    health:
      show-details: always
      show-components: always